spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personnels?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


